# Generated by Django 5.0.3 on 2024-05-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studNO', models.IntegerField()),
                ('studName', models.CharField(max_length=30)),
                ('studfee', models.IntegerField()),
                ('studAddress', models.CharField(max_length=30)),
            ],
        ),
    ]
